
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9765